Vagrant::Config.run do |config|

  config.vm.box = "ubuntu-1104-server-amd64"

  #config.vm.boot_mode = :gui

  config.vm.network("33.33.33.10")

  config.vm.customize do |vm|
    vm.memory_size = 1024
  end

  config.vm.forward_port "http", 8153, 18153
  config.vm.forward_port "ssh", 22, 10022

  config.vm.share_folder "v-data", "/home/vagrant/infoq", "../../../infoq"
  config.vm.share_folder "v-data", "/home/vagrant/repository", "../../repository"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../../chef-repo/cookbooks"
    chef.roles_path = "../../chef-repo/roles"
    chef.add_role "infoq-go"
    # chef.json = {
    #   :go => { :download_url => "http://10.0.2.2:8000" }
    # }
  end

end
