package "unzip"
package "vim"
package "curl"
package "wget"

if node['platform'] == "ubuntu"
  package "python-software-properties"
  package "build-essential"
  package "openssl"
  package "libreadline6"
  package "libreadline6-dev"
  package "zlib1g"
  package "zlib1g-dev"
  package "libssl-dev"
  package "libyaml-dev"
  package "libsqlite3-0"
  package "libsqlite3-dev"
  package "sqlite3"
  package "libxml2-dev"
  package "libxslt-dev"
  package "autoconf"
  package "libc6-dev"
  package "ncurses-dev"
  package "automake"
  package "libtool"
  package "bison"
end

include_recipe "base::source"
